name: TestNG Test Results

on:
  - workflow_dispatch
  - push

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test-results:
    name: Test Results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Generate tests
        run: cd complete && mvn clean test
      - name: starburstdata - Publish test results
        uses: starburstdata/action-testng-report@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
