name: TestNG Test Results

on:
  - workflow_dispatch
  - push

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  sample:
    name: Sample job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Generate tests
        run: cd complete && mvn clean test
      # - name: starburstdata - Publish test results
      #   uses: starburstdata/action-testng-report@v1
      #   if: always()
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: scacap/action-surefire-report@v1 - Test Results
        uses: scacap/action-surefire-report@v1
        if: always()
        with:
          report_paths: "**/surefire-reports/TEST-*.xml"
