on:
  - workflow_dispatch
  - push

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test-results:
    name: Test Results (reference)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Generate tests
        run: cd complete && mvn clean test
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "**/target/surefire-reports/*.xml"
